package com.example.ui

enum class AppLanguage(val code: String, val title: String, val isRtl: Boolean) {
    EN("en", "English", false),
    AR("ar", "العربية", true)
}

object S18Strings {
    fun get(key: String, lang: AppLanguage): String {
        return when (lang) {
            AppLanguage.AR -> arStrings[key] ?: enStrings[key] ?: key
            AppLanguage.EN -> enStrings[key] ?: key
        }
    }

    private val enStrings = mapOf(
        "app_name" to "S18_THEME",
        "tagline" to "Beautiful Themes. One Place.",
        "explore_themes" to "Explore Themes",
        "browse_companies" to "Browse Companies",
        "search_placeholder" to "Search themes, designers, companies...",
        "home" to "Home",
        "themes" to "Themes",
        "companies" to "Companies",
        "latest_themes" to "Latest Themes",
        "latest_updates" to "Latest Updates",
        "featured" to "Featured",
        "designers" to "Designers",
        "search" to "Search",
        "trending_themes" to "Trending Themes",
        "recently_updated" to "Recently Updated",
        "featured_themes" to "Featured Themes",
        "popular_designers" to "Popular Designers",
        "view_theme" to "View Theme",
        "quick_preview" to "Quick Preview",
        "view_details" to "View Details",
        "download_theme" to "Download Theme",
        "download_latest_version" to "Download Latest Version",
        "version_history" to "Version History",
        "whats_new" to "What's New",
        "preview" to "Preview",
        "comments" to "Comments",
        "share" to "Share",
        "previous" to "Previous",
        "next" to "Next",
        "close" to "Close",
        "zoom" to "Zoom",
        "updated" to "UPDATED",
        "new" to "NEW",
        "featured_badge" to "FEATURED",
        "download_opening" to "Opening Download...",
        "download_error" to "Download Link Unavailable",
        "no_themes" to "No themes available yet",
        "no_comments" to "No comments yet",
        "be_first_comment" to "Be the first to comment",
        "nickname" to "Nickname",
        "write_comment" to "Write a comment...",
        "post_comment" to "Post Comment",
        "comment_submitted_notice" to "Comment submitted for admin moderation.",
        "theme_not_found" to "Theme Not Found",
        "theme_not_found_desc" to "The theme you're looking for doesn't exist or has been removed.",
        "back_to_themes" to "Back to Themes",
        "sort_latest" to "Latest",
        "sort_most_viewed" to "Most Viewed",
        "sort_most_downloaded" to "Most Downloaded",
        "sort_recently_updated" to "Recently Updated",
        "filter_all" to "All",
        "toggle_dark_mode" to "Toggle dark mode",

        // Admin strings
        "admin" to "Admin",
        "admin_portal" to "S18 Admin Portal",
        "dashboard" to "Dashboard",
        "analytics" to "Analytics",
        "updates" to "Updates",
        "backups" to "Backups",
        "settings" to "Settings",
        "logout" to "Logout",
        "login" to "Login",
        "enter_admin_pin" to "Enter Admin Access PIN",
        "pin_placeholder" to "Default PIN: 1234",
        "add_theme" to "Add Theme",
        "edit_theme" to "Edit Theme",
        "delete_theme" to "Delete Theme",
        "duplicate" to "Duplicate",
        "publish" to "Publish",
        "hide" to "Hide",
        "draft" to "Draft",
        "published" to "Published",
        "scheduled" to "Scheduled",
        "add_version" to "Add Version",
        "manage_images" to "Manage Images",
        "save_draft" to "Save Draft",
        "publish_now" to "Publish Now",
        "schedule" to "Schedule",
        "total_themes" to "Total Themes",
        "total_companies" to "Total Companies",
        "total_designers" to "Total Designers",
        "total_views" to "Total Views",
        "total_downloads" to "Total Downloads",
        "total_comments" to "Total Comments",
        "add_company" to "Add Company",
        "add_designer" to "Add Designer",
        "pending_comments" to "Pending Comments",
        "approve" to "Approve",
        "delete" to "Delete",
        "export_backup" to "Export Backup",
        "backup_created" to "Backup created successfully",
        "theme_created_success" to "Theme created successfully",
        "theme_updated_success" to "Theme updated successfully",
        "theme_deleted_success" to "Theme deleted successfully",
        "confirm_delete_theme" to "Are you sure you want to delete this theme?",
        "action_cannot_undone" to "This action cannot be undone.",
        "company_delete_blocked" to "This company contains themes. Move or delete the themes first.",
        "cancel" to "Cancel",
        "sub_admins" to "Sub-Admins",
        "super_admin_portal" to "Super Admin Portal",
        "add_sub_admin" to "Add Sub-Admin",
        "edit_sub_admin" to "Edit Sub-Admin",
        "delete_sub_admin" to "Delete Sub-Admin",
        "fake_email_notice" to "Sub-admin email (supports internal / fake address)",
        "sub_admin_role" to "Role / Permissions",
        "sub_admin_status" to "Account Status",
        "active_status" to "Active",
        "inactive_status" to "Disabled",
        "pwa_banner_text" to "S18_THEME Web App is available — install for offline access!",
        "pwa_install_button" to "Install Now",
        "battles" to "Theme Battles",
        "theme_battles" to "Theme Battles",
        "vote_now" to "Vote Now",
        "voted" to "Voted",
        "votes" to "votes",
        "winner" to "WINNER",
        "active_battles" to "Active Battles",
        "add_battle" to "Create Battle",
        "edit_battle" to "Edit Battle",
        "delete_battle" to "Delete Battle",
        "collections" to "Collections",
        "curated_collections" to "Curated Collections",
        "add_collection" to "Add Collection",
        "edit_collection" to "Edit Collection",
        "delete_collection" to "Delete Collection",
        "notifications" to "Notifications",
        "mark_all_read" to "Mark All Read",
        "no_notifications" to "No notifications yet",
        "before_after" to "Before & After Comparison",
        "before" to "Before",
        "after" to "After",
        "coming_soon" to "COMING SOON",
        "launching_in" to "Launching in",
        "notify_me" to "Notify Me",
        "installation_guide" to "Installation Guide",
        "step" to "Step",
        "moods" to "Mood Discovery",
        "accent_color" to "Accent Color",
        "favorite" to "Favorite",
        "reactions" to "Reactions",
        "menu" to "Menu",
        "categories" to "Categories",
        "favorites" to "Favorites",
        "support_contact" to "Support & Contact Us",
        "about_us" to "About Us",
        "privacy_policy" to "Privacy Policy & Terms",
        "rate_share" to "Rate & Share App",
        "profile" to "Profile",
        "wallpapers" to "Wallpapers",
        "publish_wallpaper" to "Publish Wallpaper",
        "appearance_settings" to "App Appearance & Colors",
        "accent_theme_color" to "Primary Accent Color",
        "app_design_style" to "Cards & UI Style",
        "style_cyber" to "Cyber Neon (Default)",
        "style_minimal" to "Clean Minimalist",
        "style_glass" to "Glassmorphism Glow",
        "empty_themes_title" to "No Themes Published Yet",
        "empty_themes_desc" to "The catalog is currently empty. Use the Admin Dashboard to add your first smartphone theme!",
        "open_admin" to "Open Admin Dashboard",

        // Features 2, 4, 6
        "device_compatibility" to "Device Compatibility",
        "smart_compat_check" to "Smart Compatibility Check",
        "install_guide_title" to "Installation Guide",
        "view_install_guide" to "View Step-by-Step Guide",
        "compat_score" to "Compatibility Match",
        "detected_device" to "Detected Device",
        "ratings_and_reviews" to "Ratings & Reviews",
        "rate_this_theme" to "Rate This Theme",
        "tap_to_rate" to "Tap stars to rate",
        "your_rating" to "Your Rating",
        "write_review_optional" to "Share your thoughts about this theme (optional)...",
        "submit_rating" to "Submit Rating",
        "no_reviews_yet" to "No reviews yet. Be the first to rate this theme!",
        "reviews_count" to "Reviews",
        "verified_creator" to "Verified Creator",
        "follow_creator" to "Follow",
        "following_creator" to "Following",
        "creator_followers" to "Followers",
        "creator_themes" to "Themes",
        "creator_downloads" to "Total Downloads",
        "creator_verified_badge" to "Verified Creator",
        "installation_guides_all" to "Installation Guides & Compatibility"
    )

    private val arStrings = mapOf(
        "app_name" to "S18_THEME",
        "tagline" to "ثيماتك المفضلة في مكان واحد.",
        "explore_themes" to "استكشف الثيمات",
        "browse_companies" to "تصفح الشركات",
        "search_placeholder" to "ابحث عن الثيمات أو المصممين أو الشركات...",
        "home" to "الرئيسية",
        "themes" to "الثيمات",
        "companies" to "الشركات",
        "latest_themes" to "أحدث الثيمات",
        "latest_updates" to "آخر التحديثات",
        "featured" to "المميزة",
        "designers" to "المصممون",
        "search" to "البحث",
        "trending_themes" to "الثيمات الرائجة",
        "recently_updated" to "آخر التحديثات",
        "featured_themes" to "الثيمات المميزة",
        "popular_designers" to "أشهر المصممين",
        "view_theme" to "عرض الثيم",
        "quick_preview" to "معاينة سريعة",
        "view_details" to "عرض التفاصيل",
        "download_theme" to "تحميل الثيم",
        "download_latest_version" to "تحميل أحدث إصدار",
        "version_history" to "سجل الإصدارات",
        "whats_new" to "ما الجديد",
        "preview" to "المعاينة",
        "comments" to "التعليقات",
        "share" to "مشاركة",
        "previous" to "السابق",
        "next" to "التالي",
        "close" to "إغلاق",
        "zoom" to "تكبير",
        "updated" to "تم التحديث",
        "new" to "جديد",
        "featured_badge" to "مميز",
        "download_opening" to "جارٍ فتح رابط التحميل...",
        "download_error" to "رابط التحميل غير متاح",
        "no_themes" to "لا توجد ثيمات متاحة حاليًا",
        "no_comments" to "لا توجد تعليقات بعد",
        "be_first_comment" to "كن أول من يعلق",
        "nickname" to "الاسم المستعار",
        "write_comment" to "اكتب تعليقك...",
        "post_comment" to "نشر التعليق",
        "comment_submitted_notice" to "تم إرسال التعليق للمراجعة من قبل الإدارة.",
        "theme_not_found" to "الثيم غير موجود",
        "theme_not_found_desc" to "الثيم الذي تبحث عنه غير موجود أو تمت إزالته.",
        "back_to_themes" to "العودة إلى الثيمات",
        "sort_latest" to "الأحدث",
        "sort_most_viewed" to "الأكثر مشاهدة",
        "sort_most_downloaded" to "الأكثر تحميلًا",
        "sort_recently_updated" to "آخر التحديثات",
        "filter_all" to "الكل",
        "toggle_dark_mode" to "تبديل الوضع الداكن",

        // Admin strings
        "admin" to "لوحة التحكم",
        "admin_portal" to "بوابة إدارة S18_THEME",
        "dashboard" to "لوحة التحكم",
        "analytics" to "الإحصائيات",
        "updates" to "التحديثات",
        "backups" to "النسخ الاحتياطي",
        "settings" to "الإعدادات",
        "logout" to "تسجيل الخروج",
        "login" to "تسجيل الدخول",
        "enter_admin_pin" to "أدخل رمز مرور المشرف",
        "pin_placeholder" to "الرمز الافتراضي: 1234",
        "add_theme" to "إضافة ثيم",
        "edit_theme" to "تعديل الثيم",
        "delete_theme" to "حذف الثيم",
        "duplicate" to "نسخ",
        "publish" to "نشر",
        "hide" to "إخفاء",
        "draft" to "مسودة",
        "published" to "منشور",
        "scheduled" to "مجدول",
        "add_version" to "إضافة إصدار",
        "manage_images" to "إدارة الصور",
        "save_draft" to "حفظ كمسودة",
        "publish_now" to "نشر الآن",
        "schedule" to "جدولة",
        "total_themes" to "إجمالي الثيمات",
        "total_companies" to "إجمالي الشركات",
        "total_designers" to "إجمالي المصممين",
        "total_views" to "إجمالي المشاهدات",
        "total_downloads" to "إجمالي التحميلات",
        "total_comments" to "إجمالي التعليقات",
        "add_company" to "إضافة شركة",
        "add_designer" to "إضافة مصمم",
        "pending_comments" to "التعليقات المعلقة",
        "approve" to "اعتماد",
        "delete" to "حذف",
        "export_backup" to "تصدير نسخة احتياطية",
        "backup_created" to "تم إنشاء النسخة الاحتياطية بنجاح",
        "theme_created_success" to "تم إنشاء الثيم بنجاح",
        "theme_updated_success" to "تم تحديث الثيم بنجاح",
        "theme_deleted_success" to "تم حذف الثيم بنجاح",
        "confirm_delete_theme" to "هل أنت متأكد من حذف هذا الثيم؟",
        "action_cannot_undone" to "لا يمكن التراجع عن هذا الإجراء.",
        "company_delete_blocked" to "هذه الشركة تحتوي على ثيمات. انقل الثيمات أو احذفها أولًا.",
        "cancel" to "إلغاء",
        "sub_admins" to "المشرفون الفرعيون",
        "super_admin_portal" to "لوحة السوبر أدمن",
        "add_sub_admin" to "إضافة مشرف فرعي",
        "edit_sub_admin" to "تعديل بيانات المشرف",
        "delete_sub_admin" to "حذف حساب المشرف",
        "fake_email_notice" to "البريد الإلكتروني (يدعم الإيميلات الوهمية / الداخلية)",
        "sub_admin_role" to "صلاحيات ودور المشرف",
        "sub_admin_status" to "حالة الحساب",
        "active_status" to "نشط",
        "inactive_status" to "معطّل",
        "pwa_banner_text" to "تطبيق الويب متوفر — ثبّت S18_THEME للوصول السريع بدون إنترنت",
        "pwa_install_button" to "تثبيت الآن",
        "battles" to "معارك الثيمات",
        "theme_battles" to "معارك الثيمات",
        "vote_now" to "صوّت الآن",
        "voted" to "تم التصويت",
        "votes" to "أصوات",
        "winner" to "الفائز",
        "active_battles" to "المعارك النشطة",
        "add_battle" to "إنشاء معركة جديدة",
        "edit_battle" to "تعديل المعركة",
        "delete_battle" to "حذف المعركة",
        "collections" to "المجموعات",
        "curated_collections" to "المجموعات المميزة",
        "add_collection" to "إضافة مجموعة جديدة",
        "edit_collection" to "تعديل المجموعة",
        "delete_collection" to "حذف المجموعة",
        "notifications" to "الإشعارات",
        "mark_all_read" to "تعيين الكل كمقروء",
        "no_notifications" to "لا توجد إشعارات جديدة",
        "before_after" to "المقارنة قبل وبعد",
        "before" to "قبل",
        "after" to "بعد",
        "coming_soon" to "قريباً",
        "launching_in" to "ينطلق خلال",
        "notify_me" to "أبلغني عند الإطلاق",
        "installation_guide" to "دليل التثبيت والتشغيل",
        "step" to "الخطوة",
        "moods" to "الأمزجة والتصنيفات",
        "accent_color" to "اللون المميز",
        "favorite" to "المفضلة",
        "reactions" to "التفاعلات",
        "menu" to "القائمة",
        "categories" to "التصنيفات",
        "favorites" to "المفضلة",
        "support_contact" to "الدعم / تواصل معنا",
        "about_us" to "من نحن",
        "privacy_policy" to "سياسة الخصوصية والشروط",
        "rate_share" to "تقييم ومشاركة التطبيق",
        "profile" to "الملف الشخصي",
        "wallpapers" to "الخلفيات",
        "publish_wallpaper" to "نشر خلفية جديدة",
        "appearance_settings" to "إعدادات ومظهر التطبيق",
        "accent_theme_color" to "اللون المميز للتطبيق",
        "app_design_style" to "مظهر الكروت والواجهات",
        "style_cyber" to "سايبر نيون (الافتراضي)",
        "style_minimal" to "عصري وبسيط",
        "style_glass" to "توهج زجاجي",
        "empty_themes_title" to "لا توجد ثيمات منشورة بعد",
        "empty_themes_desc" to "قاعدة البيانات فارغة حالياً ونظيفة. يمكنك الدخول للوحة تحكم الأدمن ونشر ثيماتك الأولى بنفسك!",
        "open_admin" to "فتح لوحة تحكم الأدمن",

        // Features 2, 4, 6
        "device_compatibility" to "توافق الجهاز",
        "smart_compat_check" to "فحص التوافق الذكي",
        "install_guide_title" to "دليل التثبيت التفاعلي",
        "view_install_guide" to "عرض دليل التثبيت خطوة بخطوة",
        "compat_score" to "نسبة التوافق",
        "detected_device" to "الجهاز المكتشف",
        "ratings_and_reviews" to "التقييمات ومراجعات المستخدمين",
        "rate_this_theme" to "تقييم هذا الثيم",
        "tap_to_rate" to "اضغط على النجوم للتقييم",
        "your_rating" to "تقييمك",
        "write_review_optional" to "اكتب رأيك وتجربتك مع الثيم (اختياري)...",
        "submit_rating" to "إرسال التقييم",
        "no_reviews_yet" to "لا توجد تقييمات بعد. كن أول من يقيّم هذا الثيم!",
        "reviews_count" to "مراجعة",
        "verified_creator" to "مصمم موثق",
        "follow_creator" to "متابعة",
        "following_creator" to "تتابعه",
        "creator_followers" to "متابع",
        "creator_themes" to "ثيم",
        "creator_downloads" to "إجمالي التحميلات",
        "creator_verified_badge" to "مصمم معتمد وموثق",
        "installation_guides_all" to "أدلة التثبيت وتوافق الأجهزة"
    )
}
